GET http://localhost:3000/members 

###

GET http://localhost:3000/members/636a9737b9893995c8f1c9345wertgwretgz

###

POST http://localhost:3000/members 
Content-Type: application/json

{
    "name": "Kerim G", 
    "memberTitle": "CEO"
}

###

DELETE http://localhost:3000/members/636a95721c789babb255c743

###

PATCH http://localhost:3000/members/636a9737b98a93995c8f1c97
Content-Type: application/json

{
    "name": "Gizem G",
    "memberTitle": "Board member"
}