GET http://localhost:3000/members 

###

GET http://localhost:3000/members/636a9737b9893995c8f1c9345wertgwretgz

###
POST http://localhost:3000/members 
Content-Type: application/json

{
    "name": "Kerim G", 
    "memberTitle": "CEO"
}